gnps-classical-molecular-networking: gnps-classical-molecular-networking
masst-repository-scale-search: masst
mzmine-gc-ms-processing: mzmine
mzmine-imaging-ms-processing: mzmine
mzmine-lc-ms-processing: mzmine
sirius-canopus-class-prediction: canopus
sirius-csi-fingerid-cosmic: csi-fingerid
sirius-msnovelist-de-novo: msnovelist
sirius-zodiac-formula-annotation: sirius
